"""Add fields to categories

Revision ID: 0446fef03381
Revises: 93582a768fd6
Create Date: 2026-03-06 15:53:32.543562
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.db.types import JSONBType


revision: str = '0446fef03381'
down_revision: Union[str, None] = '93582a768fd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_material_categories', sa.Column('fields', JSONBType(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw_material_categories', 'fields')
    # ### end Alembic commands ###
