"""add_measurement_units_table

Revision ID: 0f024f5d9187
Revises: 0446fef03381
Create Date: 2026-03-06 16:49:42.955318
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0f024f5d9187'
down_revision: Union[str, None] = '0446fef03381'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('measurement_units',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_measurement_units_id'), 'measurement_units', ['id'], unique=False)
    op.create_index(op.f('ix_measurement_units_name'), 'measurement_units', ['name'], unique=True)
    op.create_index(op.f('ix_measurement_units_symbol'), 'measurement_units', ['symbol'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_measurement_units_symbol'), table_name='measurement_units')
    op.drop_index(op.f('ix_measurement_units_name'), table_name='measurement_units')
    op.drop_index(op.f('ix_measurement_units_id'), table_name='measurement_units')
    op.drop_table('measurement_units')
    # ### end Alembic commands ###
