"""add is_on_website to products

Revision ID: 1e3427a7a585
Revises: e0c03b79804d
Create Date: 2026-03-13 15:15:21.596154
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


"""add is_on_website to products

Revision ID: 1e3427a7a585
Revises: e0c03b79804d
Create Date: 2026-03-13 15:15:21.596154
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1e3427a7a585'
down_revision: Union[str, None] = 'e0c03b79804d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add as nullable first
    op.add_column('products', sa.Column('is_on_website', sa.Boolean(), nullable=True))
    
    # Update existing rows to False
    op.execute("UPDATE products SET is_on_website = FALSE")
    
    # Make it non-nullable
    op.alter_column('products', 'is_on_website', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'is_on_website')
    # ### end Alembic commands ###
