"""link_materials_to_variants

Revision ID: 41b9eceb14c2
Revises: 0f024f5d9187
Create Date: 2026-03-08 15:18:31.031319
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '41b9eceb14c2'
down_revision: Union[str, None] = '0f024f5d9187'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_materials', sa.Column('variant_id', sa.UUID(), nullable=False))
    op.add_column('product_materials', sa.Column('unit_override', sa.String(length=50), nullable=True))
    op.alter_column('product_materials', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('product_materials', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('ix_product_materials_product_id', table_name='product_materials')
    op.create_index(op.f('ix_product_materials_id'), 'product_materials', ['id'], unique=False)
    op.create_index(op.f('ix_product_materials_variant_id'), 'product_materials', ['variant_id'], unique=False)
    op.drop_constraint('product_materials_product_id_fkey', 'product_materials', type_='foreignkey')
    op.create_foreign_key(None, 'product_materials', 'product_variants', ['variant_id'], ['id'], ondelete='CASCADE')
    op.drop_column('product_materials', 'product_id')
    op.alter_column('products', 'internal_code',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.create_index(op.f('ix_products_internal_code'), 'products', ['internal_code'], unique=False)
    op.drop_column('products', 'brand')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('brand', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_products_internal_code'), table_name='products')
    op.alter_column('products', 'internal_code',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.add_column('product_materials', sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'product_materials', type_='foreignkey')
    op.create_foreign_key('product_materials_product_id_fkey', 'product_materials', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_product_materials_variant_id'), table_name='product_materials')
    op.drop_index(op.f('ix_product_materials_id'), table_name='product_materials')
    op.create_index('ix_product_materials_product_id', 'product_materials', ['product_id'], unique=False)
    op.alter_column('product_materials', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('product_materials', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_column('product_materials', 'unit_override')
    op.drop_column('product_materials', 'variant_id')
    # ### end Alembic commands ###
