"""add whatsapp_events table

Revision ID: 82069c6acdd7
Revises: e3c11afa7e1d
Create Date: 2026-03-12 12:35:58.907272
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '82069c6acdd7'
down_revision: Union[str, None] = 'e3c11afa7e1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whatsapp_events',
    sa.Column('event_type', sa.String(length=100), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whatsapp_events_id'), 'whatsapp_events', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_whatsapp_events_id'), table_name='whatsapp_events')
    op.drop_table('whatsapp_events')
    # ### end Alembic commands ###
