"""Add categories and customers

Revision ID: 93582a768fd6
Revises: 004_suppliers_raw_materials
Create Date: 2026-03-06 15:41:35.936675
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '93582a768fd6'
down_revision: Union[str, None] = '004_suppliers_raw_materials'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('tax_id', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=False)
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_index(op.f('ix_customers_name'), 'customers', ['name'], unique=False)
    op.create_index(op.f('ix_customers_tax_id'), 'customers', ['tax_id'], unique=False)
    op.create_table('raw_material_categories',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_material_categories_id'), 'raw_material_categories', ['id'], unique=False)
    op.create_index(op.f('ix_raw_material_categories_name'), 'raw_material_categories', ['name'], unique=True)
    op.drop_constraint('inventory_variant_id_key', 'inventory', type_='unique')
    op.drop_index('ix_inventory_variant_id', table_name='inventory')
    op.create_index(op.f('ix_inventory_variant_id'), 'inventory', ['variant_id'], unique=True)
    op.drop_index('ix_inventory_movements_type', table_name='inventory_movements')
    op.create_index(op.f('ix_inventory_movements_movement_type'), 'inventory_movements', ['movement_type'], unique=False)
    op.drop_constraint('uq_raw_materials_internal_code', 'raw_materials', type_='unique')
    op.drop_index('ix_raw_materials_internal_code', table_name='raw_materials')
    op.create_index(op.f('ix_raw_materials_internal_code'), 'raw_materials', ['internal_code'], unique=True)
    op.drop_constraint('uq_webhook_events_event_id', 'webhook_events', type_='unique')
    op.drop_index('ix_webhook_events_event_id', table_name='webhook_events')
    op.create_index(op.f('ix_webhook_events_event_id'), 'webhook_events', ['event_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_events_event_id'), table_name='webhook_events')
    op.create_index('ix_webhook_events_event_id', 'webhook_events', ['event_id'], unique=False)
    op.create_unique_constraint('uq_webhook_events_event_id', 'webhook_events', ['event_id'])
    op.drop_index(op.f('ix_raw_materials_internal_code'), table_name='raw_materials')
    op.create_index('ix_raw_materials_internal_code', 'raw_materials', ['internal_code'], unique=False)
    op.create_unique_constraint('uq_raw_materials_internal_code', 'raw_materials', ['internal_code'])
    op.drop_index(op.f('ix_inventory_movements_movement_type'), table_name='inventory_movements')
    op.create_index('ix_inventory_movements_type', 'inventory_movements', ['movement_type'], unique=False)
    op.drop_index(op.f('ix_inventory_variant_id'), table_name='inventory')
    op.create_index('ix_inventory_variant_id', 'inventory', ['variant_id'], unique=False)
    op.create_unique_constraint('inventory_variant_id_key', 'inventory', ['variant_id'])
    op.drop_index(op.f('ix_raw_material_categories_name'), table_name='raw_material_categories')
    op.drop_index(op.f('ix_raw_material_categories_id'), table_name='raw_material_categories')
    op.drop_table('raw_material_categories')
    op.drop_index(op.f('ix_customers_tax_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_name'), table_name='customers')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
