"""Add product categories and site config

Revision ID: ae1601a20261
Revises: 97f5c8124c1f
Create Date: 2026-03-15 11:16:33.258300
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ae1601a20261'
down_revision: Union[str, None] = '97f5c8124c1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_featured', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('products', sa.Column('is_new_arrival', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'is_new_arrival')
    op.drop_column('products', 'is_featured')
    # ### end Alembic commands ###
