"""add_product_images

Revision ID: e0c03b79804d
Revises: 82069c6acdd7
Create Date: 2026-03-12 20:25:38.220209
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.db.types import JSONBType


revision: str = 'e0c03b79804d'
down_revision: Union[str, None] = '82069c6acdd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_variants', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.add_column('products', sa.Column('images', JSONBType(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'images')
    op.drop_column('product_variants', 'image_url')
    # ### end Alembic commands ###
