"""add_whatsapp_messages_table

Revision ID: e3c11afa7e1d
Revises: 007_sales_modalities
Create Date: 2026-03-12 11:52:40.915876
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'e3c11afa7e1d'
down_revision: Union[str, None] = '007_sales_modalities'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whatsapp_messages',
    sa.Column('wa_id', sa.String(length=255), nullable=False),
    sa.Column('from_phone', sa.String(length=20), nullable=False),
    sa.Column('to_phone', sa.String(length=20), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('msg_type', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('wa_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whatsapp_messages_direction'), 'whatsapp_messages', ['direction'], unique=False)
    op.create_index(op.f('ix_whatsapp_messages_from_phone'), 'whatsapp_messages', ['from_phone'], unique=False)
    op.create_index(op.f('ix_whatsapp_messages_id'), 'whatsapp_messages', ['id'], unique=False)
    op.create_index(op.f('ix_whatsapp_messages_status'), 'whatsapp_messages', ['status'], unique=False)
    op.create_index(op.f('ix_whatsapp_messages_to_phone'), 'whatsapp_messages', ['to_phone'], unique=False)
    op.create_index(op.f('ix_whatsapp_messages_wa_id'), 'whatsapp_messages', ['wa_id'], unique=True)
    op.alter_column('purchases', 'purchase_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('purchases', 'purchase_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_index(op.f('ix_whatsapp_messages_wa_id'), table_name='whatsapp_messages')
    op.drop_index(op.f('ix_whatsapp_messages_to_phone'), table_name='whatsapp_messages')
    op.drop_index(op.f('ix_whatsapp_messages_status'), table_name='whatsapp_messages')
    op.drop_index(op.f('ix_whatsapp_messages_id'), table_name='whatsapp_messages')
    op.drop_index(op.f('ix_whatsapp_messages_from_phone'), table_name='whatsapp_messages')
    op.drop_index(op.f('ix_whatsapp_messages_direction'), table_name='whatsapp_messages')
    op.drop_table('whatsapp_messages')
    # ### end Alembic commands ###
